/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>      /* printf, scanf, NULL */
#include <stdlib.h>     /* calloc, exit, free */

static int *buffer;
JNIEXPORT jint JNICALL Java_TestValgrind_malloc(JNIEnv *env, jobject obj, jint size){
      buffer= (int*) calloc (size,sizeof(int));
      if(buffer==NULL)
          return -1;
      else
          return 0;
}
JNIEXPORT void JNICALL Java_TestValgrind_free(JNIEnv *env, jobject obj){
      free(buffer);
}